# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Variable-Watcher
version:      0.01
version_from: lib/Variable/Watcher.pm
installdirs:  site
requires:
    Attribute::Handlers:           0.04
    Log::Message:                  0
    Params::Check:                 0.07
    Test::More:                    0
    Tie::Array:                    0
    Tie::Hash:                     0
    Tie::Scalar:                   0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
